cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.index, name='homepage'),
    path('cart/', views.cart_page, name="cart_page"),
    # path('set/', views.setsession, name='set_session'),
    # path('get/', views.getsession, name='get_session'),
    # path('del/', views.delsession, name='del_session'),
    path('add', views.item_add, name='item_add'),
    path('decrement', views.item_decrement, name='item_decrement'),
    path('remove', views.remove, name='remove'),
    path('clear', views.cart_clear, name='cart_clear'),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopapp.urls', namespace="session_app")),
    path('cart/', include('cart.urls', namespace="cart_app")),
]

shopapp/urls.py
from django.urls import path
from .views import *

app_name = "shopapp"

urlpatterns = [
    path('', index, name="home"),
    path('on-cart', cart, name="on-cart"),

    path('item_add/<int:id>', add_page, name='item_add'),
    path('item_increment/<int:id>', item_increment, name='item_increment'),
    path('item_decrement/<int:id>', item_decrement, name='item_decrement'),
    path('item_remove/<int:id>', remove, name='item_remove'),
    path('cart_clear', cart_clear, name='cart_clear'),
]

cart/models.py
from django.db import models

# Create your models here.

shopapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.PositiveIntegerField()
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    objects = models.Manager()

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from .cart import Cart


def index(request):
    return render(request, 'cart/index.html')


def item_add(request):
    cart = Cart(request)
    cart.add()
    return redirect("cart:cart_page")


def item_decrement(request):
    cart = Cart(request)
    cart.decrement()
    return redirect("cart:cart_page")


def remove(request):
    cart = Cart(request)
    cart.remove()
    return redirect("cart:cart_page")


def cart_clear(request):
    cart = Cart(request)
    cart.cart_clear()
    return redirect("cart:homepage")


def cart_page(request):
    cart = Cart(request)
    item = cart.items()
    return render(request, 'cart/cart.html', {"item": item})



























# def item_add(request):
#     cart = request.session.get(settings.CART_SESSION_ID)
#     if not cart:
#         cart = request.session[settings.CART_SESSION_ID] = {}
#     print(cart)
#     cart = {
#         "name": "jamshid",
#         "age": 28,
#     }
#     print(cart['age'])
#     for key, values in cart.items():
#         if "jamshid" == values:
#             cart['age'] += 1
#             print(cart)
#     return redirect("cart_page")



# def setsession(request):
#     request.session['name'] = "jamshid"
#     request.session['sname'] = "azizov"
#     return render(request, 'cart/index.html')
#
#
# def getsession(request):
#     # name = request.session['name']
#     name = request.session.get('name', default="you name")
#     sname = request.session.get('sname', default="you surname")
#     keys = request.session.keys()
#     items = request.session.items()
#     age = request.session.setdefault('age', '28')
#     context = {
#         "name": name,
#         "sname": sname,
#         "keys": keys,
#         "items": items,
#         "age": age,
#     }
#     return render(request, 'cart/index.html', context)
#
#
# def delsession(request):
#     # if 'name' and 'sname' in request.session:
#     #     del request.session['name']
#     #     del request.session['sname']
#     # request.session.flush()
#     # request.session.clear()
#     del request.session
#     return render(request, 'cart/index.html')

shopapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Product
from .cart import Cart


def index(request):
    products = Product.objects.all()
    return render(request, 'shopapp/dist/index.html', {"products": products})


def add_page(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("shopapp:home")


def item_increment(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.add(product=product)
    return redirect("shopapp:on-cart")


def item_decrement(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.decrement(product=product)
    return redirect("shopapp:on-cart")


def remove(request, id):
    cart = Cart(request)
    product = Product.objects.get(id=id)
    cart.remove(product)
    return redirect("shopapp:on-cart")


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect("shopapp:home")


def cart(request):
    cart = Cart(request)
    items = cart.items()
    total_price = cart.get_total_price()
    count = cart.get_total_items()

    context = {
        "items": items,
        "count": count,
        "total_price": total_price,
    }
    return render(request, 'shopapp/dist/cart.html', context)

cart/templates/cart/cart.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="container">
        {{ item.name }}
        {{ item.age }}
        <a href="{% url 'cart:item_add' %}"><button>+</button></a>
        <a href="{% url 'cart:item_decrement' %}"><button>-</button></a>
        <a href="{% url 'cart:remove' %}"><button>clear</button></a>
        <div class="row">
            <h2><a href="{% url 'cart:cart_clear' %}"><button>Cart Clear</button></a></h2>
            <a href="{% url 'cart:homepage' %}">Home</a>
        </div>
    </div>
</body>
</html>

cart/templates/cart/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <h1>Session</h1>
        {{ name }}{{ sname }}<br/><hr/>
        {% for key in keys %}
            {{ key }}<br/>
        {% endfor %}<hr/>
        {% for item in items %}
            {{ item }}<br/>
        {% endfor %}<hr/>
        {% for x,y in items %}
            {{ x }} - {{ y }}<br/>
        {% endfor %}<hr/>
        <a href="{% url 'cart:item_add' %}">add</a>
    </div>
</body>
</html>

shopapp/templates/shopapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>